### Setup

In [7]:
using Pkg

Pkg.add(url="https://github.com/mppmu/BoostFractor.jl.git")
Pkg.add(url="https://github.com/bergermann/Dragoon.jl.git")
Pkg.update()

    Updating git-repo `https://github.com/mppmu/BoostFractor.jl.git`


   Resolving package versions...


   Installed FFTW ───────────── v1.7.0


   Installed CommonSolve ────── v0.2.4
   Installed ConstructionBase ─ v1.5.2
   Installed LogExpFunctions ── v0.3.24
   Installed ChainRulesCore ─── v1.16.0


    Updating `C:\Users\domin\.julia\environments\v1.9\Project.toml`
  [222d2961] + BoostFractor v0.0.0 `https://github.com/mppmu/BoostFractor.jl.git#master`
    Updating `C:\Users\domin\.julia\environments\v1.9\Manifest.toml`
  [621f4979] + AbstractFFTs v1.3.1
  [222d2961] + BoostFractor v0.0.0 `https://github.com/mppmu/BoostFractor.jl.git#master`
  [d360d2e6] + ChainRulesCore v1.16.0
  [38540f10] + CommonSolve v0.2.4
  [34da2185] + Compat v4.6.1
  [187b0558] + ConstructionBase v1.5.2
  [ffbed154] + DocStringExtensions v0.9.3
  [7a1cc6ca] + FFTW v1.7.0
  [b21f74c0] + FunctionZeros v0.2.0
⌅ [92d709cd] + IrrationalConstants v0.1.1
  [692b3bcd] + JLLWrappers v1.4.1
  [2ab3a3ac] + LogExpFunctions v0.3.24
  [1914dd2f] + MacroTools v0.5.10
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.3.0
⌅ [f2b01f46] + Roots v1.4.1
⌅ [efcf1570] + Setfield v0.8.2
⌅ [276daf66] + SpecialFunctions v1.8.8
  [f5851436] + FFTW_jll v3.3.10+0
  [1d5cc7b8] + IntelOpenMP_jll v2023.1.0+0
⌅ [856f044c] + MKL_


Precompiling project...


  ✓ CommonSolve


  ✓ Compat


  ✓ ConstructionBase
  ✓ JLLWrappers


  ✓ IrrationalConstants
  ✓ Compat → CompatLinearAlgebraExt


  ✓ FFTW_jll
  ✓ IntelOpenMP_jll
  ✓ OpenSpecFun_jll


  ✓ LogExpFunctions


  ✓ Setfield


  ✓ MKL_jll
  ✓ ChainRulesCore


  ✓ AbstractFFTs → AbstractFFTsChainRulesCoreExt


  ✓ LogExpFunctions → LogExpFunctionsChainRulesCoreExt


  ✓ Roots


  ✓ SpecialFunctions


  ✓ FunctionZeros


  ✓ FFTW


  ✓ BoostFractor
  20 dependencies successfully precompiled in 13 seconds. 17 already precompiled.
    Updating git-repo `https://github.com/bergermann/Dragoon.jl.git`

   Resolving package versions...


   Installed GR_jll ────────────── v0.72.7+0


   Installed ConcurrentUtilities ─ v2.2.0
   Installed OpenSSL ───────────── v1.4.1
   Installed Unitful ───────────── v1.14.0
   Installed RecipesPipeline ───── v0.6.12
   Installed DelimitedFiles ────── v1.9.1


   Installed HTTP ──────────────── v1.9.6


   Installed TranscodingStreams ── v0.9.13


   Installed Pixman_jll ────────── v0.42.2+0
   Installed OpenSSL_jll ───────── v1.1.21+0


   Installed StatsBase ─────────── v0.34.0
   Installed Plots ─────────────── v1.38.16


   Installed Latexify ──────────── v0.16.1
   Installed DataAPI ───────────── v1.15.0
   Installed RecipesBase ───────── v1.3.4
   Installed LLVMOpenMP_jll ────── v15.0.4+0


   Installed SortingAlgorithms ─── v1.1.1
   Installed UnitfulLatexify ───── v1.6.3


   Installed GR ────────────────── v0.72.7


    Updating `C:\Users\domin\.julia\environments\v1.9\Project.toml`
  [2528b1d8] + Dragoon v0.0.0 `https://github.com/bergermann/Dragoon.jl.git#main`
    Updating `C:\Users\domin\.julia\environments\v1.9\Manifest.toml`


  [d1d4a3ce] + BitFlags v0.1.7
  [944b1d66] + CodecZlib v0.7.1
  [35d6a980] + ColorSchemes v3.21.0
  [3da002f7] + ColorTypes v0.11.4
  [c3611d14] + ColorVectorSpace v0.9.10
  [5ae59095] + Colors v0.12.10
  [f0e56b4a] + ConcurrentUtilities v2.2.0
  [d38c429a] + Contour v0.6.2
  [9a962f9c] + DataAPI v1.15.0
  [864edb3b] + DataStructures v0.18.13
  [8bb1440f] + DelimitedFiles v1.9.1
  [2528b1d8] + Dragoon v0.0.0 `https://github.com/bergermann/Dragoon.jl.git#main`
  [c87230d0] + FFMPEG v0.4.1
  [53c48c17] + FixedPointNumbers v0.8.4
  [59287772] + Formatting v0.4.2
  [28b8d3ca] + GR v0.72.7
  [42e2da0e] + Grisu v1.0.2
  [cd3eb016] + HTTP v1.9.6
  [1019f520] + JLFzf v0.1.5
  [b964fa9f] + LaTeXStrings v1.3.0
  [23fbe1c1] + Latexify v0.16.1
  [e6f89c97] + LoggingExtras v1.0.0
  [739be429] + MbedTLS v1.1.7
  [442fdcdd] + Measures v0.3.2
  [e1d29d7a] + Missings v1.1.0
  [77ba4419] + NaNMath v1.0.2
  [4d8831e6] + OpenSSL v1.4.1
  [bac558e1] + OrderedCollections v1.6.0
  [b98c9c47] + Pipe v1.3.0


Precompiling project...

  ✓ LaTeXStrings


  ✓ Pipe
  ✓ StatsAPI
  ✓ Contour


  ✓ SimpleBufferStream
  ✓ Measures


  ✓ ConcurrentUtilities
  ✓ Unzip
  ✓ OrderedCollections


  ✓ URIs


  ✓ Grisu


  ✓ Formatting
  ✓ DataAPI
  ✓ DelimitedFiles
  ✓ BitFlags


  ✓ Scratch


  ✓ LoggingExtras


  ✓ TranscodingStreams


  ✓ Graphite2_jll
  ✓ Libmount_jll
  ✓ OpenSSL_jll
  ✓ LLVMOpenMP_jll


  ✓ UnicodeFun


  ✓ Bzip2_jll


  ✓ MbedTLS


  ✓ Xorg_libXau_jll


  ✓ libpng_jll


  ✓ RecipesBase
  ✓ libfdk_aac_jll


  ✓ LAME_jll
  ✓ LERC_jll


  ✓ fzf_jll
  ✓ JpegTurbo_jll


  ✓ Ogg_jll


  ✓ Xorg_libXdmcp_jll


  ✓ x265_jll


  ✓ x264_jll


  ✓ libaom_jll
  ✓ Zstd_jll


  ✓ Expat_jll
  ✓ LZO_jll
  ✓ Xorg_xtrans_jll


  ✓ Opus_jll


  ✓ Libiconv_jll


  ✓ Libffi_jll


  ✓ Libgpg_error_jll
  ✓ Showoff


  ✓ Wayland_protocols_jll


  ✓ Xorg_libpthread_stubs_jll


  ✓ Libuuid_jll
  ✓ Missings


  ✓ FriBidi_jll
  ✓ RelocatableFolders


  ✓ CodecZlib


  ✓ Pixman_jll


  ✓ FreeType2_jll


  ✓ JLFzf
  ✓ DataStructures


  ✓ libvorbis_jll


  ✓ Libtiff_jll
  ✓ XML2_jll


  ✓ SortingAlgorithms


  ✓ Libgcrypt_jll


  ✓ OpenSSL
  ✓ Fontconfig_jll


  ✓ Wayland_jll


  ✓ Gettext_jll


  ✓ Latexify


  ✓ ColorVectorSpace


  ✓ XSLT_jll


  ✓ Glib_jll


  ✓ Xorg_libxcb_jll


  ✓ StatsBase


  ✓ Xorg_libX11_jll
  ✓ Xorg_xcb_util_jll


  ✓ HTTP


  ✓ Xorg_libXfixes_jll
  ✓ Xorg_libxkbfile_jll
  ✓ 

Xorg_libXrender_jll
  ✓ Xorg_xcb_util_renderutil_jll
  ✓ Xorg_xcb_util_keysyms_jll
  ✓ Xorg_libXext_jll
  ✓ Xorg_xcb_util_image_jll
  ✓ Xorg_xcb_util_wm_jll


  ✓ Xorg_xkbcomp_jll


  ✓ Xorg_libXcursor_jll


  ✓ Libglvnd_jll
  ✓ Xorg_libXi_jll
  ✓ Xorg_libXrandr_jll
  ✓ Xorg_libXinerama_jll


  ✓ Cairo_jll


  ✓ Xorg_xkeyboard_config_jll


  ✓ GLFW_jll


  ✓ ColorSchemes


  ✓ HarfBuzz_jll


  ✓ xkbcommon_jll


  ✓ Qt5Base_jll


  ✓ libass_jll


  ✓ FFMPEG_jll


  ✓ FFMPEG


  ✓ GR_jll


  ✓ GR


  ✓ PlotUtils


  ✓ PlotThemes


  ✓ RecipesPipeline


  ✓ Unitful


  ✓ UnitfulLatexify


  ✓ Plots


  ✓ Dragoon


  ✓ Plots → UnitfulExt
  110 dependencies successfully precompiled in 81 seconds. 43 already precompiled.


    Updating registry at `C:\Users\domin\.julia\registries\General.toml`
    Updating git-repo `https://github.com/mppmu/BoostFractor.jl.git`


    Updating git-repo `https://github.com/bergermann/Dragoon.jl.git`


  No Changes to `C:\Users\domin\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\domin\.julia\environments\v1.9\Manifest.toml`

In [8]:
using Dragoon

In [29]:
#number of discs in the booster
n = 20

#initial disc configuration
#findpeak tries to find an equidistant configuration with a peak at f
initdist = findpeak(22.025e9,n)

#generate frequencies for calculation and for plotting
freqs = genFreqs(22.025e9,50e6; length=10) #optimize on these frequencies
freqsplot = genFreqs(22.025e9,150e6; length=1000)

#initialize physical properties of the booster
booster = AnalyticalBooster(initdist)
#=
Booster(
    pos,              disc positions
    ndisk,            disc number
    thickness,        disc thickness
    epsilon,          disc epsilon
    vmotor,           motor speed
    maxlength,        maximum allowed booster length (not implemented yet)
    timestamp,        booster operation time
    summedtraveltime, summed motor operation time
    codetimestamp     code runtime
)
=#

#initialize storage of measurements
hist = initHist(booster,10000,freqs,ObjAnalytical)
#                           ^ length, should be at least the larger of (n^2, search steps)
;

Objective Value: -243.3, Timestamp: 2023-06-18T22:02:22.758


In [30]:
b1 = copy(booster.pos); display(b1)

20-element Vector{Float64}:
 0.007209715011297336
 0.01541943002259467
 0.023629145033892004
 0.03183886004518934
 0.04004857505648668
 0.04825829006778401
 0.05646800507908135
 0.06467772009037868
 0.07288743510167603
 0.08109715011297336
 0.08930686512427068
 0.097516580135568
 0.10572629514686534
 0.11393601015816267
 0.12214572516946
 0.13035544018075734
 0.13856515519205465
 0.14677487020335206
 0.15498458521464936
 0.1631943002259467

In [31]:
p = zeros(booster.ndisk)
g = zeros(booster.ndisk)
h = zeros(booster.ndisk,booster.ndisk)

updateHist!(booster,hist,freqs,ObjAnalytical)

deriv = Derivator2(1e-3,1e-3,"double")

secondDerivative(g,h,booster,hist,freqs,ObjAnalytical,(1e-3,1e-3,"double"))

b2 = copy(booster.pos); display(booster.pos)

20-element Vector{Float64}:
 0.007209715011297334
 0.01541943002259467
 0.023629145033892004
 0.03183886004518934
 0.04004857505648668
 0.04825829006778401
 0.05646800507908135
 0.06467772009037868
 0.07288743510167603
 0.08109715011297336
 0.08930686512427068
 0.097516580135568
 0.10572629514686534
 0.11393601015816267
 0.12214572516946
 0.13035544018075734
 0.13856515519205465
 0.14677487020335206
 0.15498458521464936
 0.1631943002259467

In [38]:
import Dragoon.move
args = (1e-3,1e-3,"double")
objFunction = ObjAnalytical

updateHist!(booster,hist,freqs,objFunction)
move(booster,[(1,args[1])])

if args[3] == "double"
    for i in 1:booster.ndisk
        updateHist!(booster,hist,freqs,objFunction)
        move(booster,[(i,-2*args[1])])
        updateHist!(booster,hist,freqs,objFunction)

        g[i] = (hist[2].objvalue-hist[1].objvalue)/(2*args[1])

        if i != booster.ndisk
            move(booster,[(i,args[1]),(i+1,args[1])])
        else
            move(booster,[(i,args[1])])
        end
    end

    for i in 1:booster.ndisk, j in 1:booster.ndisk
        move(booster,[(i,args[2]),(j,args[2])])
        updateHist!(booster,hist,freqs,objFunction)

        move(booster,[(j,-args[2])])
        updateHist!(booster,hist,freqs,objFunction)

        move(booster,[(i,-args[2]),(j,args[2])])
        updateHist!(booster,hist,freqs,objFunction)

        move(booster,[(j,-args[2])])
        updateHist!(booster,hist,freqs,objFunction)
        
        h[i,j] = (hist[4].objvalue-hist[3].objvalue-
                    hist[2].objvalue+hist[1].objvalue)/(args[2]^2)
    end
end

In [47]:
updateHist!(booster,hist,freqs,objFunction; force=true)

In [45]:
Dragoon.shiftdown!(hist)

In [50]:
booster.pos[1] = 1.
hist

10000-element Vector{State}:
 State([1.0, 0.01541943002259467, 0.023629145033892004, 0.03183886004518934, 0.04004857505648668, 0.04825829006778401, 0.05646800507908135, 0.06467772009037868, 0.07288743510167603, 0.08109715011297336, 0.08930686512427068, 0.097516580135568, 0.10572629514686534, 0.11393601015816267, 0.12214572516946, 0.13035544018075734, 0.13856515519205465, 0.14677487020335206, 0.15498458521464936, 0.1631943002259467], -243.30220663023675, Dates.DateTime("2023-06-19T07:16:02.758"))
 State([1.0, 0.01541943002259467, 0.023629145033892004, 0.03183886004518934, 0.04004857505648668, 0.04825829006778401, 0.05646800507908135, 0.06467772009037868, 0.07288743510167603, 0.08109715011297336, 0.08930686512427068, 0.097516580135568, 0.10572629514686534, 0.11393601015816267, 0.12214572516946, 0.13035544018075734, 0.13856515519205465, 0.14677487020335206, 0.15498458521464936, 0.1631943002259467], -243.30220663023263, Dates.DateTime("2023-06-18T22:02:22.758"))
 State([1.0, 0.015419430022

### Optimizer

In [3]:
#=
how to use

linesearch(                     directly modifies booster.pos
    booster,                    
    hist,                       
    freqs,                      frequency range to optimize on
    α,                          base step length e.g. motorspeed*measurementfrequency
    (objective,[options]),      objective function
    (solver,[options]),         provides step direction p
    (derivative,[options]),     provides derivatives for use by solver
    (step,[options]),           calculates steplength
    (search,[options]),         search mode
    (unstuckinator,[options]);  tries to unstuck system from bad local minima
    ϵgrad=0,                    terminate if norm(gradient) falls below this value,
    maxiter=100,                maximum allowed iterations,
    showtrace=false,            wether to print progress,
    showevery=1,                only print every i iterations,
    unstuckisiter=true          wether an unstucking iteration counts towards maxiter
                                    warning! can run endlessly if false
)

returns trace, access with
trace[iteration].x      disc position
                .obj    objective value
                .g      gradient
                .h      hessian
                .t      timestamp
                .T      summed travel time
=#

In [4]:
trace = linesearch(booster,hist,freqs,booster.vmotor*1e-3,
                    ObjAnalytical,
                    SolverNewton("cholesky"),
                    Derivator2(1e-5,1e-6,"double"),
                    StepNorm("unit"),
                    SearchExtendedSteps(2000),
                    UnstuckDont;
                    ϵgrad=0.,maxiter=Int(2e1),showtrace=true);

20-element Vector{Float64}:
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7
 1.216511033151163e7

20×20 Matrix{Float64}:
 -2.43302e14  -2.43302e14  -2.43302e14  …  -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14  …  -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14  …  -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14  -2.43302e14     -2.43302e14  -2.43302e14
 -2.43302e14  -2.43302e14

LinearAlgebra.PosDefException: PosDefException: matrix is not positive definite; Cholesky factorization failed.

In [5]:
#obtain result, booster is now in optimized position
#pos2dist(booster.pos)     #in distance space
booster.pos               #in position space

20-element Vector{Float64}:
 0.007209715011297335
 0.01541943002259467
 0.023629145033892004
 0.03183886004518935
 0.040048575056486686
 0.04825829006778402
 0.056468005079081354
 0.06467772009037867
 0.07288743510167602
 0.08109715011297335
 0.08930686512427066
 0.09751658013556799
 0.10572629514686532
 0.11393601015816265
 0.12214572516945998
 0.13035544018075737
 0.13856515519205467
 0.1467748702033521
 0.1549845852146494
 0.16319430022594672

In [6]:
#get handy output
plt = analyse(hist,trace,freqsplot; freqs=freqs,div=10)

#savefig(plt[i],"cool_epic_result_wow.svg")

UndefVarError: UndefVarError: `trace` not defined